### PR TITLE
Contents session 1

### PR DESCRIPTION
**Pull request by bafain**

### CODE REVIEW

**Comment by AndreasLoow** [comment]
Where is "generic (primitive) recursion" discussed? Do you mean general recursion?

**Edit**: Hm, it's mentioned in the tutorial -- but only briefly. Not many hits on Google either.

**Edit 2**: Seems to (in the tutorial) refer to the `Fixpoint` and `match` constructs, where you can express recursive algorithms in readable form rather than using e.g. `nat_rec` or similar. If so, I think this wording is confusing in a table of contents.

**Comment by bafain** [comment]
Yes, the term was taken from the tutorial.

**Comment by AndreasLoow** [comment]
Hm, sorry but where is well-founded recursion covered in the material? Imho, things mentioned in "contents" should be covered in "material". Maybe it makes sense to include well-founded recursion in the session 1; but, if so, I think something explaining what well-founded recursion in Coq is should be included also (in the material section).

Maybe this is a good idea in general ... i.e., an item in the contents list should always mention where in the material it's covered.

**Comment by bafain** [comment]
The material covers how to define functions (`fun`), how to define primitive recursive functions (`rec`) and how to define generic primitive/well-founded/structural recursive functions (`fix`, different terminology used by the tutorial, the reference manual and the winter school notes).

**Comment by AndreasLoow** [comment]
Ah, ok, I thought (for some reason) that you were referring to things like those mentioned in e.g. [5.3 in A Tutorial on [Co-]Inductive Types in Coq](http://www.labri.fr/perso/casteran/RecTutorial.pdf#page=44) (`Acc` etc.).

**Pull request closed without merging**
